name: weather
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/
  fonts:
    - family: Encode Sans
      fonts:
        - asset: assets/fonts/EncodeSansExpanded-Light.ttf
          weight: 300
        - asset: assets/fonts/EncodeSansExpanded-Regular.ttf
          weight: 400
        - asset: assets/fonts/EncodeSansExpanded-SemiBold.ttf
          weight: 600
